### ISSUE TITLE
Wizard line extends outside of the body panel

### ISSUE THREAD

**Issue by holtjonathan** [angular-wizard/angular-wizard#195]
Is this library supported any longer?  I have an issue where I added a wizard on one of my pages that is within a panel.  Everything seems to be working fine except that the line that connects the 5 circles together extends out passed the panel body.    Please check out this example of what I mean: http://imgur.com/a/olPvC

Any ideas on how to fix this?

**Comment by jacobscarter** [comment]
Yes you can customize the CSS to style this, if you provide a link to the page your wizard is on I can help you with that, however "out of the box" the line does not expand past the body panel so this is not an issue with the repo code, Ill close this issue but let me know if you want me to look at your CSS.

**Comment by holtjonathan** [comment]
@jacobscarter My issue is that the line DOES expand outside of the container that it is in.  It goes across the entire page instead of staying within the panel (like it should).  I'll see if I can recreate the issue on codepen or something so that you can see the code.  I feel like 'out of the box' the wizard shouldn't expand outside of the panel/container that it is in.

**Comment by jacobscarter** [comment]
Out of the box the line does not expans, I understand what your issue is, what I was saying is that the wizard CSS out of the box does not have that issue, I will re-open the ticket and wait for you code example, if the line is expanding to far from just a plain vanilla install of the wizard, then we can fix it, anything beyond that is custom css for your project.

**Comment by jacobscarter** [comment]
Closing because no example was provided.
